### ISSUE TITLE
Move settings to setup.cfg and use setuptools-scm

### ISSUE THREAD

**Issue by prjemian** [prjemian/ym2021_prj#10]
Move settings to setup.cfg and use setuptools-scm per https://github.com/bluesky/ophyd/pull/1065

**Comment by prjemian** [comment]
Move config from .flake8, pytest.ini, setup.py, coveragerc, and requirements*.txt to setup.cfg and adopt setuptools-scm instead of versioneer (which will also allow us to delete MANIFEST.in).

Rewrite CI to share steps in less workflows and test the packaging.

**Comment by prjemian** [comment]
Good Q&A: https://stackoverflow.com/questions/62983756/what-is-pyproject-toml-file-for

**Comment by prjemian** [comment]
latest setuptools docs: https://setuptools.pypa.io

Python packaging is evolving, this is keeping up.

**Comment by prjemian** [comment]
note the branch starts with number `20`, should have been 10, oh well

**Comment by prjemian** [comment]
Try a different workflow action that allows pre-configured conda environment:

```yaml
    - name: Build and upload the conda packages
      uses: uibcdf/action-build-and-upload-conda-packages@v1.1.0
      with:
        meta_yaml_dir: conda/
        python-version: ${{ matrix.python-version }}
        user: prjemian
        label: "auto"
        token: ${{ secrets.ANACONDA_TOKEN }}
```

Not happy with it since it ends with 

```

Conda packages uploading
  /home/runner/work/_temp/0c85fa7c-7a46-4a56-abaf-172d0ba18986.sh: line 14: label:: command not found
  The trigger type synchronize is not compatible with 
  Error: Process completed with exit code 1.
```

Note that message is incomplete due to syntax error in bash script where the backticks denote an executable command:

```bash
echo "The trigger type synchronize is not compatible with `label: auto`"
```

**Comment by prjemian** [comment]
Originally used https://github.com/marketplace/actions/publish-anaconda-package-to-anaconda-org but wanted to switch since it kept insisting it could not find the `setuptools-scm` package.

**Comment by prjemian** [comment]
Try another workflow action: [`openalea/action-build-publish-anaconda`](https://github.com/openalea/action-build-publish-anaconda)

**Comment by prjemian** [comment]
Discovered [act](https://github.com/nektos/act), when installed locally, will run your github workflows locally in docker containers.

**Comment by prjemian** [comment]
cannot find the problems with this one:

```yml
    - name: Determine publish
      uses: haya14busa/action-cond@v1
      id: publish
      with:
        cond: ${{ contains(github.ref, 'stable') || startsWith(github.ref, 'refs/heads/v') }}
        if_true: 'true'
        if_false: 'false'

    - name: Build and Publish
      uses: openalea/action-build-publish-anaconda@v0.1.2
      with:
        conda: conda
        mamba: true
        python: ${{ matrix.python-minor-version }}
        numpy: '20.0'
        channels: conda-forge, prjemian
        token: ${{ secrets.ANACONDA_TOKEN }}
        # publish: ${{ steps.publish.outputs.value }}
        # label: main
        publish: 'true'
        label: dev
```

**Comment by prjemian** [comment]
The original action:

```yaml
    - name: Build Anaconda package and Publish to Anaconda.org
      uses: BEFH/anaconda-publish@v1.5.1
      with:
        subDir: 'conda'
        channels: 'conda-forge -c prjemian'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
        publish: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}
        test_all: ${{(github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')) || (github.ref == 'refs/heads/main')}}
        convert_win: false
        convert_osx: false
```

**Comment by prjemian** [comment]
Re-try, with slight modifications:

```yml
    - name: Build Anaconda package and Publish to Anaconda.org
      # uses: BEFH/anaconda-publish@v1.5.1
      uses: paskino/conda-package-publish-action@master
      # uses: lauramurgatroyd/test-gh-actions@mambabuild
      with:
        subDir: 'conda'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
        # channels: 'conda-forge -c prjemian'
        # publish: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') }}
        publish: true
        # test_all: ${{(github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')) || (github.ref == 'refs/heads/main')}}
        test_all: true
        convert_win: false
        convert_osx: false
        # test_pyver: "3.9"
```

still ends with

```
[Publish conda package to Anaconda/build] [DEBUG] Starting container: 8879266de11dc567302c94a7712d2b8b4273b1496cb984c03aef6a04bf35ee32
[Publish conda package to Anaconda/build]   | + set -o pipefail
[Publish conda package to Anaconda/build]   | + install_apt_packages
[Publish conda package to Anaconda/build]   | + '[' '!' -z '' ']'
[Publish conda package to Anaconda/build]   | + go_to_build_dir
[Publish conda package to Anaconda/build]   | + '[' '!' -z conda ']'
[Publish conda package to Anaconda/build]   | + cd conda
[Publish conda package to Anaconda/build]   | + check_if_meta_yaml_file_exists
[Publish conda package to Anaconda/build]   | + '[' '!' -f meta.yaml ']'
[Publish conda package to Anaconda/build]   | + build_and_test_package
[Publish conda package to Anaconda/build]   | + '[' true = true ']'
[Publish conda package to Anaconda/build]   | + eval conda build '{' -c 'conda-forge}' --output-folder . .
[Publish conda package to Anaconda/build]   | ++ conda build '{' -c 'conda-forge}' --output-folder . .
[Publish conda package to Anaconda/build]   | /entrypoint.sh: line 27: conda: command not found
```

**Comment by prjemian** [comment]
This one builds:

```yaml
    - name: Anaconda-Action
      id: build
      uses: fdiblen/anaconda-action@0.1.7
      with:
        activate-env: true
        channels: conda-forge
        env-file-name: 'environment.yml'
        env-name: conda-build-env
        publish: false
        publish-channel: prjemian
        python-version: 3.9

    # Use the output from the `build` step
    - name: Get the action execution time
      run: |
        echo "The time was ${{ steps.build.outputs.time }}"
        echo "The conda version is ${{ steps.build.outputs.conda_version }}"
        echo "The python version is ${{ steps.build.outputs.python_version }}"
```

... but, confidence is low since it reports that it used python 2.7

```bash
(bluesky_2022_3) prjemian@zap:~/.../prjemian/ym2021_prj$ act  -j build 2>&1 | tee /tmp/act.log
[Publish conda package to Anaconda/build] 🚀  Start image=catthehacker/ubuntu:act-latest
[Publish conda package to Anaconda/build]   🐳  docker pull image=catthehacker/ubuntu:act-latest platform= username= forcePull=false
[Publish conda package to Anaconda/build]   🐳  docker create image=catthehacker/ubuntu:act-latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Publish conda package to Anaconda/build]   🐳  docker run image=catthehacker/ubuntu:act-latest platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Publish conda package to Anaconda/build]   ☁  git clone 'https://github.com/fdiblen/anaconda-action' # ref=0.1.7
[Publish conda package to Anaconda/build] ⭐ Run Main Checkout
[Publish conda package to Anaconda/build]   🐳  docker cp src=/home/prjemian/Documents/projects/prjemian/ym2021_prj/. dst=/home/prjemian/Documents/projects/prjemian/ym2021_prj
[Publish conda package to Anaconda/build] close /tmp/act1867810445: file already closed
[Publish conda package to Anaconda/build]   ✅  Success - Main Checkout
[Publish conda package to Anaconda/build] ⭐ Run Main Anaconda-Action
[Publish conda package to Anaconda/build]   🐳  docker pull image=act-fdiblen-anaconda-action-0-1-7-dockeraction:latest platform= username= forcePull=false
[Publish conda package to Anaconda/build]   🐳  docker create image=act-fdiblen-anaconda-action-0-1-7-dockeraction:latest platform= entrypoint=[] cmd=["environment.yml"]
[Publish conda package to Anaconda/build]   🐳  docker run image=act-fdiblen-anaconda-action-0-1-7-dockeraction:latest platform= entrypoint=[] cmd=["environment.yml"]
[Publish conda package to Anaconda/build]   ⚙  ::set-output:: python_version=2.7.16
[Publish conda package to Anaconda/build]   ✅  Success - Main Anaconda-Action
[Publish conda package to Anaconda/build] ⭐ Run Main Get the action execution time
[Publish conda package to Anaconda/build]   🐳  docker exec cmd=[bash -l /var/run/act/workflow/2] user= workdir=
[Publish conda package to Anaconda/build]   | The time was 
[Publish conda package to Anaconda/build]   | The conda version is 
[Publish conda package to Anaconda/build]   | The python version is 2.7.16
[Publish conda package to Anaconda/build]   ✅  Success - Main Get the action execution time
[Publish conda package to Anaconda/build] 🏁  Job succeeded
```

**Comment by prjemian** [comment]
Looking as if we need to do this ourselves.  Hrmph.

**Comment by prjemian** [comment]
Looking through the [GitHub Actions marketplace](https://github.com/marketplace?type=actions&query=conda+) for `conda` (rather than `anaconda` as used above), found a new action: [`build-conda`](https://github.com/marketplace/actions/build-conda) (source: https://github.com/cascode-labs/build-conda-action) which looks promising.

**Comment by prjemian** [comment]
```yaml
    - name: Build conda package
      uses: cascode-labs/build-conda-action@main
      with:
        recipe_path: conda
        build_options: "-c defaults -c conda-forge"
```

runs to success, albeit slowly.
